@startuml TTHHH

package Acceso{

    class Usuario{
        -codigo : int
        -password: string
    }

    class Compania{
        -codigo: int
        -nombre: string
        -direccion: string
    }
}

package Seleccionar{
    class Empleado{
        codigo: int
        apellidoPaterno: string
        apellidoMaterno: string
        nombres: string
        numeroCedula: string
        direccion: string
        telefono1: int
        telefono2: int
        carnetIESS: int
        fechaNacimiento: date
        fechaIngreso: date
        cuentaBancaria: string
        banco: string
        boniEspecial: double
        sueldoBase: double
        fondoReserva: double
        reIngreso: bool
        fechaReIngreso: date
    }
}

package Seleccionar.Catalogos{

    enum TipoTrabajador <<enumeration>>{
        ADMINISTRATIVO
        FINANZAS
        VENTAS
        PRODUCCION
        MANTENIMIENTO
        SEGURIDAD
        LIMPIEZA
    }

    enum StatusTrabajador <<enumeration>>{
        ACTIVO
        INACTIVO
    }

    enum TipoContrato <<enumeration>>{
        INDEFINIDO
        PLAZO_FIJO
        TEMPORAL
        JORNADA_PARCIAL
    }

    enum TipoComision <<enumeration>>{
        BLANCO
        VENTAS
        CANTIDAD
        BENEFICIO
    }

    enum EstadoCivil <<enumeration>>{
        SOLTERO
        CASADO
        DIVORCIADO
        VIUDO
    }

    enum TipoCuenta <<enumeration>>{
        AHORROS
        CORRIENTE
    }

    enum Sexo <<enumeration>>{
        MASCULINO
        FEMENINO
    }

}

package Mantenimiento{

    class CentroCostos{
        -codigo: int
        -descripcion: string
    }

    class ConceptoNomina{
        -codigo: int
        -descripcion: string
        -prioridad: int
        -grabadoIESS: bool
        -trabAfecImpRenta: bool
        -movExcepcion: int
        -emprsAfecIESS: bool
    }

    class CategoriaOcupacional{
        -codigo : int
        -descripcion : string
    }

    class RegistroHistoricoNomina{
        -codigo: int
        -descripcion: string
    }

    class GestionCuentasContable{
        -codigo: int
        -descripcion: string
    }

    class CambiarCierreNomina{
        -codigo: int
        -descripcion: string
    }

    class NivelSalarial{
        -codigo: int
        -descripcion: string
    }

    class ParametrosPersonal{
        -codigo: int
        -descripcion: string
    }

    class Ocupaciones{
        -codigo: int
        -descripcion: string
    }

    class Correlativos{
        -codigo: int
        -descripcion: string
    }

}

package Mantenimiento.Catalogos{

    enum TipoOperacion <<enumeration>>{
        INGRESOS
        EGRESOS
    }

}

@enduml